/*
Nnwdaf_AnalyticsInfo

Nnwdaf_AnalyticsInfo Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 

API version: 1.1.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// PlmnId struct for PlmnId
type PlmnId struct {
	Mcc string `json:"mcc"`
	Mnc string `json:"mnc"`
}

// NewPlmnId instantiates a new PlmnId object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlmnId(mcc string, mnc string) *PlmnId {
	this := PlmnId{}
	this.Mcc = mcc
	this.Mnc = mnc
	return &this
}

// NewPlmnIdWithDefaults instantiates a new PlmnId object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlmnIdWithDefaults() *PlmnId {
	this := PlmnId{}
	return &this
}

// GetMcc returns the Mcc field value
func (o *PlmnId) GetMcc() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Mcc
}

// GetMccOk returns a tuple with the Mcc field value
// and a boolean to check if the value has been set.
func (o *PlmnId) GetMccOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mcc, true
}

// SetMcc sets field value
func (o *PlmnId) SetMcc(v string) {
	o.Mcc = v
}

// GetMnc returns the Mnc field value
func (o *PlmnId) GetMnc() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Mnc
}

// GetMncOk returns a tuple with the Mnc field value
// and a boolean to check if the value has been set.
func (o *PlmnId) GetMncOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mnc, true
}

// SetMnc sets field value
func (o *PlmnId) SetMnc(v string) {
	o.Mnc = v
}

func (o PlmnId) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["mcc"] = o.Mcc
	}
	if true {
		toSerialize["mnc"] = o.Mnc
	}
	return json.Marshal(toSerialize)
}

type NullablePlmnId struct {
	value *PlmnId
	isSet bool
}

func (v NullablePlmnId) Get() *PlmnId {
	return v.value
}

func (v *NullablePlmnId) Set(val *PlmnId) {
	v.value = val
	v.isSet = true
}

func (v NullablePlmnId) IsSet() bool {
	return v.isSet
}

func (v *NullablePlmnId) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlmnId(val *PlmnId) *NullablePlmnId {
	return &NullablePlmnId{value: val, isSet: true}
}

func (v NullablePlmnId) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlmnId) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


