/*
 * Nnwdaf_AnalyticsInfo
 *
 * Nnwdaf_AnalyticsInfo Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type BatteryIndication struct {

	BatteryInd bool `json:"batteryInd,omitempty"`

	ReplaceableInd bool `json:"replaceableInd,omitempty"`

	RechargeableInd bool `json:"rechargeableInd,omitempty"`
}

// AssertBatteryIndicationRequired checks if the required fields are not zero-ed
func AssertBatteryIndicationRequired(obj BatteryIndication) error {
	return nil
}

// AssertRecurseBatteryIndicationRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of BatteryIndication (e.g. [][]BatteryIndication), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseBatteryIndicationRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aBatteryIndication, ok := obj.(BatteryIndication)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertBatteryIndicationRequired(aBatteryIndication)
	})
}
