/*
 * Nnwdaf_AnalyticsInfo
 *
 * Nnwdaf_AnalyticsInfo Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type EventReportingRequirement struct {

	Accuracy *Accuracy `json:"accuracy,omitempty"`

	StartTs *time.Time `json:"startTs,omitempty"`

	EndTs *time.Time `json:"endTs,omitempty"`

	SampRatio int32 `json:"sampRatio,omitempty"`

	MaxObjectNbr int32 `json:"maxObjectNbr,omitempty"`

	MaxSupiNbr int32 `json:"maxSupiNbr,omitempty"`

	TimeAnaNeeded *time.Time `json:"timeAnaNeeded,omitempty"`
}
