/*
 * Nnwdaf_AnalyticsInfo
 *
 * Nnwdaf_AnalyticsInfo Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// CongestionType - Possible values are - USER_PLANE: The congestion analytics type is User Plane.  - CONTROL_PLANE: The congestion analytics type is Control Plane. - USER_AND_CONTROL_PLANE: The congestion analytics type is User Plane and Control Plane. 
type CongestionType struct {
}

// AssertCongestionTypeRequired checks if the required fields are not zero-ed
func AssertCongestionTypeRequired(obj CongestionType) error {
	return nil
}

// AssertRecurseCongestionTypeRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of CongestionType (e.g. [][]CongestionType), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseCongestionTypeRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aCongestionType, ok := obj.(CongestionType)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertCongestionTypeRequired(aCongestionType)
	})
}
