/*
 * Nnwdaf_AnalyticsInfo
 *
 * Nnwdaf_AnalyticsInfo Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Identifies an Ethernet flow
type EthFlowDescription struct {

	DestMacAddr string `json:"destMacAddr,omitempty"`

	EthType string `json:"ethType"`

	FDesc string `json:"fDesc,omitempty"`

	FDir *Ts29512NpcfSmPolicyControlYamlcomponentsschemasFlowDirection `json:"fDir,omitempty"`

	SourceMacAddr *Ts29571CommonDataYamlcomponentsschemasMacAddr48 `json:"sourceMacAddr,omitempty"`

	VlanTags []string `json:"vlanTags,omitempty"`

	SrcMacAddrEnd *Ts29571CommonDataYamlcomponentsschemasMacAddr48 `json:"srcMacAddrEnd,omitempty"`

	DestMacAddrEnd *Ts29571CommonDataYamlcomponentsschemasMacAddr48 `json:"destMacAddrEnd,omitempty"`
}
