/*
 * Nnwdaf_AnalyticsInfo
 *
 * Nnwdaf_AnalyticsInfo Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type QosSustainabilityInfo struct {

	AreaInfo *NetworkAreaInfo `json:"areaInfo,omitempty"`

	StartTs *time.Time `json:"startTs,omitempty"`

	EndTs *time.Time `json:"endTs,omitempty"`

	QosFlowRetThd *RetainabilityThreshold `json:"qosFlowRetThd,omitempty"`

	RanUeThrouThd string `json:"ranUeThrouThd,omitempty"`

	Snssai *Snssai `json:"snssai,omitempty"`

	Confidence int32 `json:"confidence,omitempty"`
}
