/*
 * Nnwdaf_AnalyticsInfo
 *
 * Nnwdaf_AnalyticsInfo Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type TimeWindow struct {

	StartTime Object `json:"startTime"`

	StopTime Object `json:"stopTime"`
}

// AssertTimeWindowRequired checks if the required fields are not zero-ed
func AssertTimeWindowRequired(obj TimeWindow) error {
	elements := map[string]interface{}{
		"startTime": obj.StartTime,
		"stopTime": obj.StopTime,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseTimeWindowRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of TimeWindow (e.g. [][]TimeWindow), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseTimeWindowRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aTimeWindow, ok := obj.(TimeWindow)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertTimeWindowRequired(aTimeWindow)
	})
}
