/*
 * Nnwdaf_AnalyticsInfo
 *
 * Nnwdaf_AnalyticsInfo Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Represents the event filters used to identify the requested analytics.
type EventFilter struct {

	AnySlice bool `json:"anySlice,omitempty"`
	// Identification(s) of network slice to which the subscription belongs.
	Snssais []Snssai `json:"snssais,omitempty"`

	AppIds []string `json:"appIds,omitempty"`

	Dnns []string `json:"dnns,omitempty"`

	Dnais []string `json:"dnais,omitempty"`

	NetworkArea *NetworkAreaInfo `json:"networkArea,omitempty"`

	NfInstanceIds []string `json:"nfInstanceIds,omitempty"`

	NfSetIds []string `json:"nfSetIds,omitempty"`

	NfTypes []NfType `json:"nfTypes,omitempty"`

	NsiIdInfos []NsiIdInfo `json:"nsiIdInfos,omitempty"`

	QosRequ *QosRequirement `json:"qosRequ,omitempty"`

	NwPerfTypes []NetworkPerfType `json:"nwPerfTypes,omitempty"`

	BwRequs []BwRequirement `json:"bwRequs,omitempty"`

	ExcepIds []ExceptionId `json:"excepIds,omitempty"`

	ExptAnaType *ExpectedAnalyticsType `json:"exptAnaType,omitempty"`

	ExptUeBehav *ExpectedUeBehaviourData `json:"exptUeBehav,omitempty"`
}
