/*
 * Nnwdaf_AnalyticsInfo
 *
 * Nnwdaf_AnalyticsInfo Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// NsiIdInfo - Represents the S-NSSAI and the optionally associated Network Slice Instance(s).
type NsiIdInfo struct {

	Snssai Snssai `json:"snssai"`

	NsiIds []string `json:"nsiIds,omitempty"`
}

// AssertNsiIdInfoRequired checks if the required fields are not zero-ed
func AssertNsiIdInfoRequired(obj NsiIdInfo) error {
	elements := map[string]interface{}{
		"snssai": obj.Snssai,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertSnssaiRequired(obj.Snssai); err != nil {
		return err
	}
	return nil
}

// AssertRecurseNsiIdInfoRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of NsiIdInfo (e.g. [][]NsiIdInfo), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseNsiIdInfoRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aNsiIdInfo, ok := obj.(NsiIdInfo)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertNsiIdInfoRequired(aNsiIdInfo)
	})
}
