/*
 * Nnwdaf_AnalyticsInfo
 *
 * Nnwdaf_AnalyticsInfo Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type HfcNodeId struct {

	HfcNId string `json:"hfcNId"`
}

// AssertHfcNodeIdRequired checks if the required fields are not zero-ed
func AssertHfcNodeIdRequired(obj HfcNodeId) error {
	elements := map[string]interface{}{
		"hfcNId": obj.HfcNId,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseHfcNodeIdRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of HfcNodeId (e.g. [][]HfcNodeId), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseHfcNodeIdRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aHfcNodeId, ok := obj.(HfcNodeId)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertHfcNodeIdRequired(aHfcNodeId)
	})
}
