/*
 * Nnwdaf_AnalyticsInfo
 *
 * Nnwdaf_AnalyticsInfo Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GlobalRanNodeId struct {

	PlmnId *PlmnId `json:"plmnId"`

	N3IwfId string `json:"n3IwfId,omitempty"`

	GNbId *GNbId `json:"gNbId,omitempty"`

	NgeNbId string `json:"ngeNbId,omitempty"`

	WagfId string `json:"wagfId,omitempty"`

	TngfId string `json:"tngfId,omitempty"`

	Nid string `json:"nid,omitempty"`

	ENbId string `json:"eNbId,omitempty"`
}
