/*
 * Nnwdaf_AnalyticsInfo
 *
 * Nnwdaf_AnalyticsInfo Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ScheduledCommunicationTime1 struct {
	// Identifies the day(s) of the week. If absent, it indicates every day of the week.
	DaysOfWeek []int32 `json:"daysOfWeek,omitempty"`

	TimeOfDayStart *Ts29571CommonDataYamlcomponentsschemasTimeOfDay `json:"timeOfDayStart,omitempty"`

	TimeOfDayEnd *Ts29571CommonDataYamlcomponentsschemasTimeOfDay `json:"timeOfDayEnd,omitempty"`
}
