/*
 * Nnwdaf_AnalyticsInfo
 *
 * Nnwdaf_AnalyticsInfo Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RetainabilityThreshold struct {

	RelFlowNum int32 `json:"relFlowNum,omitempty"`

	RelTimeUnit *TimeUnit `json:"relTimeUnit,omitempty"`

	RelFlowRatio int32 `json:"relFlowRatio,omitempty"`
}
