/*
 * Nnwdaf_AnalyticsInfo
 *
 * Nnwdaf_AnalyticsInfo Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type NfStatus struct {

	StatusRegistered int32 `json:"statusRegistered,omitempty"`

	StatusUnregistered int32 `json:"statusUnregistered,omitempty"`

	StatusUndiscoverable int32 `json:"statusUndiscoverable,omitempty"`
}
