/*
 * Nnwdaf_AnalyticsInfo
 *
 * Nnwdaf_AnalyticsInfo Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type TimeUnitAnyOf string

// List of TimeUnitAnyOf
const (
	MINUTE TimeUnitAnyOf = "MINUTE"
	HOUR TimeUnitAnyOf = "HOUR"
	DAY TimeUnitAnyOf = "DAY"
)

// AssertTimeUnitAnyOfRequired checks if the required fields are not zero-ed
func AssertTimeUnitAnyOfRequired(obj TimeUnitAnyOf) error {
	return nil
}

// AssertRecurseTimeUnitAnyOfRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of TimeUnitAnyOf (e.g. [][]TimeUnitAnyOf), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseTimeUnitAnyOfRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aTimeUnitAnyOf, ok := obj.(TimeUnitAnyOf)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertTimeUnitAnyOfRequired(aTimeUnitAnyOf)
	})
}
