/*
 * Nnwdaf_AnalyticsInfo
 *
 * Nnwdaf_AnalyticsInfo Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type NetworkPerfInfo struct {

	NetworkArea *NetworkAreaInfo `json:"networkArea"`

	NwPerfType *NetworkPerfType `json:"nwPerfType"`

	RelativeRatio int32 `json:"relativeRatio,omitempty"`

	AbsoluteNum int32 `json:"absoluteNum,omitempty"`

	Confidence int32 `json:"confidence,omitempty"`
}
