/*
 * Nnwdaf_AnalyticsInfo
 *
 * Nnwdaf_AnalyticsInfo Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type ExpectedUeBehaviourData struct {

	StationaryIndication *StationaryIndication `json:"stationaryIndication,omitempty"`

	CommunicationDurationTime int32 `json:"communicationDurationTime,omitempty"`

	PeriodicTime int32 `json:"periodicTime,omitempty"`

	ScheduledCommunicationTime *ScheduledCommunicationTime1 `json:"scheduledCommunicationTime,omitempty"`

	ScheduledCommunicationType *ScheduledCommunicationType `json:"scheduledCommunicationType,omitempty"`
	// Identifies the UE's expected geographical movement. The attribute is only applicable in 5G.
	ExpectedUmts []LocationArea `json:"expectedUmts,omitempty"`

	TrafficProfile *TrafficProfile `json:"trafficProfile,omitempty"`

	BatteryIndication *BatteryIndication `json:"batteryIndication,omitempty"`

	ValidityTime *time.Time `json:"validityTime,omitempty"`
}
