/*
 * Nnwdaf_AnalyticsInfo
 *
 * Nnwdaf_AnalyticsInfo Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type SvcExperience struct {

	Mos float32 `json:"mos,omitempty"`

	UpperRange float32 `json:"upperRange,omitempty"`

	LowerRange float32 `json:"lowerRange,omitempty"`
}

// AssertSvcExperienceRequired checks if the required fields are not zero-ed
func AssertSvcExperienceRequired(obj SvcExperience) error {
	return nil
}

// AssertRecurseSvcExperienceRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of SvcExperience (e.g. [][]SvcExperience), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseSvcExperienceRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aSvcExperience, ok := obj.(SvcExperience)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertSvcExperienceRequired(aSvcExperience)
	})
}
