/*
 * Nnwdaf_AnalyticsInfo
 *
 * Nnwdaf_AnalyticsInfo Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type LocationArea struct {

	// Identifies a list of geographic area of the user where the UE is located.
	GeographicAreas []Object `json:"geographicAreas,omitempty"`

	// Identifies a list of civic addresses of the user where the UE is located.
	CivicAddresses []Object `json:"civicAddresses,omitempty"`

	NwAreaInfo Object `json:"nwAreaInfo,omitempty"`
}

// AssertLocationAreaRequired checks if the required fields are not zero-ed
func AssertLocationAreaRequired(obj LocationArea) error {
	return nil
}

// AssertRecurseLocationAreaRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of LocationArea (e.g. [][]LocationArea), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseLocationAreaRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aLocationArea, ok := obj.(LocationArea)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertLocationAreaRequired(aLocationArea)
	})
}
