/*
 * Nnwdaf_AnalyticsInfo
 *
 * Nnwdaf_AnalyticsInfo Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ScheduledCommunicationTime1 struct {

	// Identifies the day(s) of the week. If absent, it indicates every day of the week.
	DaysOfWeek []int32 `json:"daysOfWeek,omitempty"`

	TimeOfDayStart Object `json:"timeOfDayStart,omitempty"`

	TimeOfDayEnd Object `json:"timeOfDayEnd,omitempty"`
}

// AssertScheduledCommunicationTime1Required checks if the required fields are not zero-ed
func AssertScheduledCommunicationTime1Required(obj ScheduledCommunicationTime1) error {
	return nil
}

// AssertRecurseScheduledCommunicationTime1Required recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ScheduledCommunicationTime1 (e.g. [][]ScheduledCommunicationTime1), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseScheduledCommunicationTime1Required(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aScheduledCommunicationTime1, ok := obj.(ScheduledCommunicationTime1)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertScheduledCommunicationTime1Required(aScheduledCommunicationTime1)
	})
}
