/*
 * Nnwdaf_AnalyticsInfo
 *
 * Nnwdaf_AnalyticsInfo Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type AccuracyAnyOf string

// List of AccuracyAnyOf
const (
	LOW AccuracyAnyOf = "LOW"
	HIGH AccuracyAnyOf = "HIGH"
)

// AssertAccuracyAnyOfRequired checks if the required fields are not zero-ed
func AssertAccuracyAnyOfRequired(obj AccuracyAnyOf) error {
	return nil
}

// AssertRecurseAccuracyAnyOfRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of AccuracyAnyOf (e.g. [][]AccuracyAnyOf), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseAccuracyAnyOfRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aAccuracyAnyOf, ok := obj.(AccuracyAnyOf)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertAccuracyAnyOfRequired(aAccuracyAnyOf)
	})
}
