/*
 * Nnwdaf_AnalyticsInfo
 *
 * Nnwdaf_AnalyticsInfo Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Accuracy - Possible values are - LOW: Low accuracy. - HIGH: High accuracy. 
type Accuracy struct {
}

// AssertAccuracyRequired checks if the required fields are not zero-ed
func AssertAccuracyRequired(obj Accuracy) error {
	return nil
}

// AssertRecurseAccuracyRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Accuracy (e.g. [][]Accuracy), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseAccuracyRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aAccuracy, ok := obj.(Accuracy)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertAccuracyRequired(aAccuracy)
	})
}
