/*
 * Nnwdaf_AnalyticsInfo
 *
 * Nnwdaf_AnalyticsInfo Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Possible values are   - UP: Up trend of the exception level.   - DOWN: Down trend of the exception level.   - UNKNOW: Unknown trend of the exception level.   - STABLE: Stable trend of the exception level. 
type ExceptionTrend struct {
}
