/*
 * Nnwdaf_AnalyticsInfo
 *
 * Nnwdaf_AnalyticsInfo Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Represents the network slice and optionally the associated network slice instance and the load level information.
type NsiLoadLevelInfo struct {

	LoadLevelInformation int32 `json:"loadLevelInformation"`

	Snssai *Snssai `json:"snssai"`

	NsiId string `json:"nsiId,omitempty"`
}
