/*
 * Nnwdaf_AnalyticsInfo
 *
 * Nnwdaf_AnalyticsInfo Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ScheduledCommunicationTypeAnyOf string

// List of ScheduledCommunicationTypeAnyOf
const (
	DOWNLINK_ONLY ScheduledCommunicationTypeAnyOf = "DOWNLINK_ONLY"
	UPLINK_ONLY ScheduledCommunicationTypeAnyOf = "UPLINK_ONLY"
	BIDIRECTIONAL ScheduledCommunicationTypeAnyOf = "BIDIRECTIONAL"
)

// AssertScheduledCommunicationTypeAnyOfRequired checks if the required fields are not zero-ed
func AssertScheduledCommunicationTypeAnyOfRequired(obj ScheduledCommunicationTypeAnyOf) error {
	return nil
}

// AssertRecurseScheduledCommunicationTypeAnyOfRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ScheduledCommunicationTypeAnyOf (e.g. [][]ScheduledCommunicationTypeAnyOf), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseScheduledCommunicationTypeAnyOfRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aScheduledCommunicationTypeAnyOf, ok := obj.(ScheduledCommunicationTypeAnyOf)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertScheduledCommunicationTypeAnyOfRequired(aScheduledCommunicationTypeAnyOf)
	})
}
