/*
 * Nnwdaf_AnalyticsInfo
 *
 * Nnwdaf_AnalyticsInfo Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type LineTypeAnyOf string

// List of LineTypeAnyOf
const (
	DSL LineTypeAnyOf = "DSL"
	PON LineTypeAnyOf = "PON"
)

// AssertLineTypeAnyOfRequired checks if the required fields are not zero-ed
func AssertLineTypeAnyOfRequired(obj LineTypeAnyOf) error {
	return nil
}

// AssertRecurseLineTypeAnyOfRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of LineTypeAnyOf (e.g. [][]LineTypeAnyOf), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseLineTypeAnyOfRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aLineTypeAnyOf, ok := obj.(LineTypeAnyOf)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertLineTypeAnyOfRequired(aLineTypeAnyOf)
	})
}
