/*
 * Nnwdaf_AnalyticsInfo
 *
 * Nnwdaf_AnalyticsInfo Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TrafficCharacterization struct {

	Dnn string `json:"dnn,omitempty"`

	Snssai *Snssai `json:"snssai,omitempty"`

	AppId string `json:"appId,omitempty"`

	FDescs []IpEthFlowDescription `json:"fDescs,omitempty"`

	UlVol int64 `json:"ulVol,omitempty"`

	UlVolVariance float32 `json:"ulVolVariance,omitempty"`

	DlVol int64 `json:"dlVol,omitempty"`

	DlVolVariance float32 `json:"dlVolVariance,omitempty"`
}
