/*
 * Nnwdaf_AnalyticsInfo
 *
 * Nnwdaf_AnalyticsInfo Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// NetworkAreaInfo - Describes a network area information in which the NF service consumer requests the number of UEs.
type NetworkAreaInfo struct {

	// Contains a list of E-UTRA cell identities.
	Ecgis []Ecgi `json:"ecgis,omitempty"`

	// Contains a list of NR cell identities.
	Ncgis []Ncgi `json:"ncgis,omitempty"`

	// Contains a list of NG RAN nodes.
	GRanNodeIds []GlobalRanNodeId `json:"gRanNodeIds,omitempty"`

	// Contains a list of tracking area identities.
	Tais []Tai `json:"tais,omitempty"`
}

// AssertNetworkAreaInfoRequired checks if the required fields are not zero-ed
func AssertNetworkAreaInfoRequired(obj NetworkAreaInfo) error {
	for _, el := range obj.Ecgis {
		if err := AssertEcgiRequired(el); err != nil {
			return err
		}
	}
	for _, el := range obj.Ncgis {
		if err := AssertNcgiRequired(el); err != nil {
			return err
		}
	}
	for _, el := range obj.GRanNodeIds {
		if err := AssertGlobalRanNodeIdRequired(el); err != nil {
			return err
		}
	}
	for _, el := range obj.Tais {
		if err := AssertTaiRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseNetworkAreaInfoRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of NetworkAreaInfo (e.g. [][]NetworkAreaInfo), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseNetworkAreaInfoRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aNetworkAreaInfo, ok := obj.(NetworkAreaInfo)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertNetworkAreaInfoRequired(aNetworkAreaInfo)
	})
}
