/*
 * Nnwdaf_AnalyticsInfo
 *
 * Nnwdaf_AnalyticsInfo Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type NfLoadLevelInformation struct {

	NfType *NfType `json:"nfType"`

	NfInstanceId string `json:"nfInstanceId"`

	NfSetId string `json:"nfSetId,omitempty"`

	NfStatus *NfStatus `json:"nfStatus,omitempty"`

	NfCpuUsage int32 `json:"nfCpuUsage,omitempty"`

	NfMemoryUsage int32 `json:"nfMemoryUsage,omitempty"`

	NfStorageUsage int32 `json:"nfStorageUsage,omitempty"`

	NfLoadLevelAverage int32 `json:"nfLoadLevelAverage,omitempty"`

	NfLoadLevelpeak int32 `json:"nfLoadLevelpeak,omitempty"`

	Snssai *Snssai `json:"snssai,omitempty"`

	Confidence int32 `json:"confidence,omitempty"`
}
